markdown:     rdiscount
permalink:    /:year/:month/:day/:title/
pygments:     true
paginate:     5
images:       /images

name: Hadi Hariri
description: Rambling of mostly technical nature
url: http://hadihariri.com